GET http://localhost:3001/api/ping

###

GET http://localhost:3001/api/patients

###

POST http://localhost:3001/api/patients
content-type: application/json

{
  "name":"asd",
  "occupation":"asd",
  "ssn":"asd",
  "dateOfBirth":"1999-12-12",
  "gender":"male"
}

###

GET http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667