GET http://localhost:3001/api/ping

###

GET http://localhost:3001/api/patients

###

POST http://localhost:3001/api/patients
content-type: application/json

{
  "name":"asd",
  "occupation":"asd",
  "ssn":"asd",
  "dateOfBirth":"asd",
  "gender":"male"
}