POST http://localhost:3003/api/blogs
content-Type: application/json

{
  "title": "Test",
  "author": "testauthor",
  "url": "testurl",
  "likes": "10"
}

###
POST http://localhost:3003/api/blogs
content-Type: application/json

{
  "dummy": "true"
}

###

GET http://localhost:3003/api/blogs